#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Convert CommonJS polytree.bundle.js to ES module polytree.bundle.browser.js.
 * This creates a browser-compatible ES module that can be imported using ES6 import syntax.
 */

console.log('Creating browser ES module bundle...');

// Read the CommonJS bundle.
const bundlePath = path.join(__dirname, '..', 'polytree.bundle.js');
const browserBundlePath = path.join(__dirname, '..', 'polytree.bundle.browser.js');

if (!fs.existsSync(bundlePath)) {
    console.error('Error: polytree.bundle.js not found. Run npm run build:node first.');
    process.exit(1);
}

let content = fs.readFileSync(bundlePath, 'utf8');

// 1. Replace destructured require of three with ES module import.
//    CoffeeScript outputs patterns like: ({Vector2, Vector3, ...} = require("three"));
//    and also multi-line patterns like:
//    ({
//      Plane: ThreePlane
//    } = require("three"));
//    Handle both single-line and multi-line patterns.
const threeRequireSingleLineRegex = /\(\{([^}]+)\} = require\("three"\)\);/g;
const threeRequireMultiLineRegex = /\(\{\s*([^}]+)\s*\} = require\("three"\)\);/gs;

let allThreeIdentifiers = [];

// Handle single-line patterns
let match;
while ((match = threeRequireSingleLineRegex.exec(content)) !== null) {
    const identifiers = match[1]
        .split(',')
        .map(s => s.trim())
        .filter(Boolean);
    
    identifiers.forEach(id => {
        if (id.includes(':')) {
            const [original, alias] = id.split(':').map(s => s.trim());
            allThreeIdentifiers.push(`${original} as ${alias}`);
        } else {
            allThreeIdentifiers.push(id);
        }
    });
}

// Handle multi-line patterns
while ((match = threeRequireMultiLineRegex.exec(content)) !== null) {
    const identifiers = match[1]
        .replace(/\s+/g, ' ') // Normalize whitespace
        .split(',')
        .map(s => s.trim())
        .filter(Boolean);
    
    identifiers.forEach(id => {
        if (id.includes(':')) {
            const [original, alias] = id.split(':').map(s => s.trim());
            allThreeIdentifiers.push(`${original} as ${alias}`);
        } else {
            allThreeIdentifiers.push(id);
        }
    });
}

// Remove all require("three") statements (both single-line and multi-line)
content = content.replace(/\(\{[^}]*\} = require\("three"\)\);\n?/gs, '');

// Add single consolidated import statement at the beginning if we found any
if (allThreeIdentifiers.length) {
    const importStatement = `import { ${allThreeIdentifiers.join(', ')} } from "three";\n`;
    // Insert after the first generated CoffeeScript comment
    content = content.replace(/(\/\/ Generated by CoffeeScript [^\n]*\n)/, `$1${importStatement}`);
}

// 2. Remove imported identifiers from the first giant CoffeeScript var declaration line to avoid redeclaration.
if (allThreeIdentifiers.length) {
    const lines = content.split('\n');
    // Extract just the identifier names (without aliases) for variable cleanup
    const cleanIdentifiers = allThreeIdentifiers.map(id => {
        if (id.includes(' as ')) {
            return id.split(' as ')[1].trim(); // Use the alias name
        }
        return id.trim();
    });
    const idSet = new Set(cleanIdentifiers);
    
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].startsWith('var ')) {
            // Support multiple consecutive CoffeeScript generated var lines.
            const decl = lines[i].slice(4).replace(/;$/, '');
            let parts = decl.split(',').map(p => p.trim()).filter(Boolean);
            const filtered = parts.filter(p => !idSet.has(p));
            if (filtered.length !== parts.length) {
                lines[i] = filtered.length ? ('var ' + filtered.join(', ') + ';') : '';
            }
        }
    }
    // Remove any blank lines created by eliminating entire var declarations.
    content = lines.filter(l => l !== '').join('\n');
}

// Find all module.exports assignments and collect them.
const moduleExports = [];
const exportRegex = /module\.exports\.(\w+) = (\w+);/g;
let exportMatch;

while ((exportMatch = exportRegex.exec(content)) !== null) {
    moduleExports.push({ name: exportMatch[1], value: exportMatch[2] });
}

// Remove all module.exports property assignment lines (named re-exports).
content = content.replace(/module\.exports\.\w+ = \w+;\n?/g, '');

// Remove the composite CommonJS export object if present (we'll supply pure ESM exports).
content = content.replace(/module\.exports\s*=\s*\{[\s\S]*?\};\n?/g, '');

// Find the main default export (usually the last large assignment).
// Look for patterns like "module.exports = Something" or similar.
const defaultExportMatch = content.match(/(\w+) = (function\([^)]*\)[\s\S]*?)(?=\n\w+\s*=|\nmodule\.exports|\n$)/);
let defaultExportName = 'Polytree'; // fallback

// If we can find the main Polytree class/function definition, use that.
const polytreeMatch = content.match(/Polytree = (function\([^)]*\)[\s\S]*?)(?=\n\w+\s*=|\nmodule\.exports|\n$)/);

if (polytreeMatch) {
    defaultExportName = 'Polytree';
}

// Add ES module exports at the end (dedupe names in case of prior duplicates).
const seen = new Set();
let esExports = '\n// ES module exports\n';
esExports += `export default ${defaultExportName};\n`;

moduleExports.forEach(exp => {
    if (!seen.has(exp.name)) {
        esExports += `export { ${exp.value} as ${exp.name} };\n`;
        seen.add(exp.name);
    }
});

content += esExports;

// Write the browser bundle.
fs.writeFileSync(browserBundlePath, content);

console.log(`Browser ES module bundle created: ${browserBundlePath}`);
console.log(`Exports: default (${defaultExportName}) + ${moduleExports.length} named exports`);