#!/usr/bin/env bash
cat \
  app/io/imports.js \
  app/etc/variables.js \
  app/etc/helpers.js \
  app/etc/operations.js \
  app/polytree.js \
  app/csg/unite.js \
  app/csg/subtract.js \
  app/csg/intersect.js \
  app/async/csg.js \
  app/geo/plane.js \
  app/geo/polygon.js \
  app/geo/triangle.js \
  app/geo/vertex.js \
  app/geo/mesh.js \
  app/io/exports.js \
  > polytree.bundle.js
